### PR TITLE
base: revert to alpine 3.9

### LINKED ISSUE #88: fail to get ssh key from Github
dns at [::1] not work
image

### LINKED ISSUE #179: github authorization fails
During install if you specify a github user on boot we try to download the SSH key before networking is actually fully initialized and it fails.

### LINKED ISSUE #183: Failed to connect to socket /run/dbus/system_bus_socket
My service interacts with a hardware device on the host and hence requires privileged access.
I have given privileged permission to pod, i can see t /run/dbus/system_bus_socket . file on the host but seeing this  error in pod logs

```
Inserting the driver ax99100-4.15.0-62-generic.ko into kernel...
insmod: ERROR: could not load module /opt/pyfarm/asix-driver/ax99100-4.15.0-62-generic.ko: No such file or directory
Setting the network speed of BR...
Error 2
Can't open /dev/ttyF0
Copying wpantund configuration...
Restarting DBUS to use updated wpantund config...
Failed to get D-Bus connection: Operation not permitted
Restarting systemd-logind to prevent slow login...
Failed to get D-Bus connection: Operation not permitted
Creating bq0 network interface...
./driver-init.sh: line 26: ip: command not found
./driver-init.sh: line 27: ip: command not found
./driver-init.sh: line 28: ip: command not found
Starting wpantund in background...
wpantund[17]: Starting wpantund 0.08.00d (Sep 12 2019 07:31:08) . . .
wpantund[17]: 	BUILD_VERSION = f84579f
wpantund[17]: Configuration file "/etc/wpantund.conf" read.
wpanctl.c:571: Requirement Failed (Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory)
Setting network parameters...
wpanctl.c:571: Requirement Failed (Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory)
wpantund[17]: DBUSIPCServer.cpp:70: Requirement Failed (Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory)
wpantund[17]: Unable to start DBUSIPCServer "std::exception"
wpantund[17]: Running as root without dropping privileges!
```

### PR DESCRIPTION
**Pull request by dweomer**
Reverts to alpine 3.9 for the base build. This side-steps:
- connman segfaulting after mostly setting up the NIC
- dbus-daemon failing to start

Additionally, this includes:
- removal of the `apk` executable
- forked openrc `net-online` script that actually works
- establishes default runlevel boot order
  - (network-online) -> [cloud-config] -> ccapply -> k3s-service
with `network-online` attempted but not preventing bootup of downstream services if it fails and the optional `cloud-config` running before ccapply if present

Fixes #183
Fixes #179
Fixes #88

### CODE REVIEW

**Comment by dweomer** [comment]
Still need to verify that this fixes a number of other issues.

File: overlay/etc/init.d/net-online [hunk 1]
```diff
@@ -0,0 +1,72 @@
...
+	provide network-online
+	keyword -docker -jail -lxc -openvz -prefix -systemd-nspawn -uml -vserver
+}
+
+get_interfaces()
+{
+	local ifname iftype
+	for ifname in /sys/class/net/*; do
+		[ -h "${ifname}" ] || continue
+		[ -e "/sys/devices/virtual/net/${ifname##*/}" ] && continue
```
Comment (dweomer) [inline overlay/etc/init.d/net-online]: This right ignores virtual devices such as `lo` and any bridges. This may be a problem longer term?

Comment (ibuildthecloud) [reply overlay/etc/init.d/net-online]: Do you have a link to the original file so I can do a diff

Comment (dweomer) [reply overlay/etc/init.d/net-online]: https://github.com/OpenRC/openrc/blob/0.39.2/init.d/net-online.in

**Comment by brandon099** [comment]
Thought I'd chime in here. Just built an ISO from this PR branch to test it out, and it did fix the issues I was having with my specific setup (Intel NUC with slow-ish NIC) and correctly waits for network to be available.

File: overlay/etc/init.d/net-online [hunk 2]
```diff
@@ -0,0 +1,72 @@
...
+	need sysfs
+	provide network-online
+	keyword -docker -jail -lxc -openvz -prefix -systemd-nspawn -uml -vserver
+}
+
+get_interfaces()
+{
+	local ifname iftype
+	for ifname in /sys/class/net/*; do
+		[ -h "${ifname}" ] || continue
```
Comment (ibuildthecloud) [inline overlay/etc/init.d/net-online]: i'd drop this line

File: overlay/etc/init.d/net-online [hunk 3]
```diff
@@ -0,0 +1,72 @@
...
+	timeout=${timeout:-120}
+	[ $timeout -eq 0 ] && infinite=true || infinite=false
+	while $infinite || [ $timeout -gt 0 ]; do
+	       carriers=0
+	       configured=0
+	       ifcount=0
+		for dev in ${interfaces}; do
+			[ -e /sys/class/net/$dev ] || continue
+		: $((ifcount += 1))
+		read carrier < /sys/class/net/$dev/carrier >/dev/null 2>&1 || carrier=
```
Comment (ibuildthecloud) [inline overlay/etc/init.d/net-online]: would probably drop these changes

File: overlay/etc/init.d/net-online [hunk 4]
```diff
@@ -0,0 +1,72 @@
...
+		[ "$carrier" = 1 ] && : $((carriers += 1))
+		read operstate < /sys/class/net/$dev/operstate >/dev/null 2>&1 || operstate=
+		[ "$operstate" = up ] && : $((configured += 1))
+	       done
+	       [ $configured -ge 1 ] && [ $carriers -ge 1 ] && break
+	       sleep 1
+	       : $((timeout -= 1))
+	done
+	! $infinite && [ $timeout -eq 0 ] && rc=1
+	if [ $rc -eq 0 ] && yesno ${include_ping_test:-yes}; then
```
Comment (ibuildthecloud) [inline overlay/etc/init.d/net-online]: i'd put this in the conf.d file.  Also, not drop the legacy check.

File: overlay/etc/init.d/net-online [hunk 5]
```diff
@@ -0,0 +1,72 @@
...
+	       ifcount=0
+		for dev in ${interfaces}; do
+			[ -e /sys/class/net/$dev ] || continue
+		: $((ifcount += 1))
+		read carrier < /sys/class/net/$dev/carrier >/dev/null 2>&1 || carrier=
+		[ "$carrier" = 1 ] && : $((carriers += 1))
+		read operstate < /sys/class/net/$dev/operstate >/dev/null 2>&1 || operstate=
+		[ "$operstate" = up ] && : $((configured += 1))
+	       done
+	       [ $configured -ge 1 ] && [ $carriers -ge 1 ] && break
```
Comment (ibuildthecloud) [inline overlay/etc/init.d/net-online]: would probably do ${SOMEVAR:-ifcount} so we can configure the number of required devices to be online.  And we can default to 1.
